services:
  nuxt:
    image: node:20-alpine
    container_name: nuxt-me
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - "3001:3000"   # Используем другой порт чтобы не конфликтовать с wedding
    networks:
      - web-network
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_OPTIONS=--max-old-space-size=512
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

networks:
  web-network:
    external: true
