# docker-compose.prod.yml
services:
  nuxt:
    image: node:20-alpine
    container_name: nuxt-me
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - "3001:3000"
    networks:
      - web-network
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=512
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  web-network:
    external: true
